name: corn_addiction
description: A comprehensive addiction recovery app focused on helping users overcome pornography addiction through tracking, community support, and professional guidance.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.0.5

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  shimmer: ^3.0.0

  # Charts & Visualization
  fl_chart: ^0.66.2
  table_calendar: ^3.0.9

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  flutter_animate: ^4.5.0
  animate_do: any
  
  # Markdown & Sharing
  flutter_markdown: ^0.6.18
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/
    - assets/animations/